### ISSUE TITLE
The image not working with docker-compose

### ISSUE THREAD

**Issue by Puneet-Mathur** [vmware/powerclicore#36]
The image when used in the docker-compose.yml creates the container which exits immediately and not able to run. When it is started it again exits. Below is the yaml for the docker-compose.yml

powerclicore:
  image: vmware/powerclicore

**Comment by tenthirtyam** [comment]
Use:

```yaml
services:
 powerclicore:
   image: vmware/powerclicore
   tty: true
```

Then:

```console
docker compose up -d
```

Recommend: `close/resolved`

cc @nklinkachevAtVMware 

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
